using System.Text.Json;
using CRS.Application;
using CRS.Domain;
using CRS.Infrastructure;
var root=Path.Combine(Path.GetTempPath(),"CRS-Layers-"+Guid.NewGuid().ToString("N"));
var store=TestStores.Create(root);
var oldJson="""{"Year":2025,"Broker":"FUTU","Summary":{"DividendCny":100,"InterestCny":25,"GainCny":200,"DividendInterestTax":25,"GainTax":40,"ForeignCredit":5,"SupplementTax":60},"SnapshotId":"SYNTHETIC-OLD"}""";
var old=JsonSerializer.Deserialize<CalculationResult>(oldJson)!; store.Save(old);
if (store.Load(old.SnapshotId).Summary.SupplementTax!=60m || store.History().Single().Broker!="FUTU") throw new Exception("旧结果 JSON / 历史索引不兼容。");
var trade=new Trade(new("SYNTHETIC","DEMO","USD"),"DEMO",DateTimeOffset.UtcNow,true,"BUY",1,1,1,0,-1,"B","synthetic",1,"STK",null);
var session=new CalculationResult { Year=2025,Summary=new(0,0,0,0,0,0,0),SnapshotId="SYNTHETIC-SESSION",SessionTrades=[trade],ImportedTradeCount=1 };
store.Save(session);
var loaded=store.Load(session.SnapshotId);
if (loaded.SessionTrades.Count!=0 || loaded.ImportedTradeCount!=1 || JsonSerializer.Serialize(session).Contains("SessionTrades")) throw new Exception("未选择完整快照却持久化交易明细。");
var config=Path.Combine(root,"config");Directory.CreateDirectory(config);
File.WriteAllText(Path.Combine(config,"exchange_rate.json"),"""{"2025":{"USD":7,"CNY":1}}""");
File.WriteAllText(Path.Combine(config,"exchange_rate_sources.json"),"{}");
var rates=new ExchangeRates(config);
if (rates.ForYear(2025).Count!=2 || rates.ForYear(2024).Count!=0 || rates.Get(2025,"USD").SourceConfirmed) throw new Exception("汇率列表猜测了来源或缺失年度。");
Console.WriteLine("Infrastructure 验证通过：旧 JSON、交易隐私、年度汇率列表（3 项）。");
await SettingsChecks.RunAsync(root);
HistoryPagingChecks.Run(root);
await AnnualAggregationChecks.RunAsync(root);
await ForeignCreditChecks.RunAsync(root);
await VaultChecks.RunAsync(root);
await MfaChecks.RunAsync(root);
